USE WeatherData;

CREATE TABLE IF NOT EXISTS Temperature (
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TempF DECIMAL(8,3) NOT NULL,
    TempC DECIMAL(8,3) NOT NULL,
    Humidity DECIMAL(8,3) NOT NULL,
    Timestamp DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Rain (
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RainIn DECIMAL(11,8) NOT NULL,
    RainCm DECIMAL(11,8) NOT NULL,
    Timestamp DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS WindSpeed (
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AvgKmh DECIMAL(11,8) NOT NULL,
    AvgMph DECIMAL(11,8) NOT NULL,
    GustKmh DECIMAL(11,8) NOT NULL,
    GustMph DECIMAL(11,8) NOT NULL,
    Timestamp DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS WindDirection (
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Direction DECIMAL(11,8) NOT NULL,
    Timestamp DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS AirPressure (
  Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Pressure DECIMAL(11,8) NOT NULL,
  Timestamp DATETIME NOT NULL
);